name: Daily Commit Bot

on:
  schedule:
    # Runs daily at 10:00 PM UTC (6:00 PM EST)
    - cron: '0 22 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Create daily commit
      run: |
        echo "Commit: $(date)" >> output.txt
        git add output.txt
        git commit -m "Commit: $(date)"
        git push 